### ISSUE TITLE
Errors about decorators are not valid

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow-hilla-hybrid-example#6]
I got the following frontend compilation errors, when starting the application from `main` branch:

```
INFO 12375 --- [onPool-worker-4] c.v.b.devserver.AbstractDevServerRunner  : Started Vite. Time: 6779ms
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   ?  Local:   http://127.0.0.1:54079/VAADIN/
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Error:   Failed to scan for dependencies from entries:
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   .../flow-hilla-hybrid-example/frontend/generated/vaadin.ts
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   ? [ERROR] Decorators are not valid here
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     frontend/generated/jar-resources/dev-tools-database.ts:19:2:
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       19 ?   @state()
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :          ?   ^
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : ? [ERROR] Decorators are not valid here
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     frontend/generated/jar-resources/dev-tools-database.ts:22:2:
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       22 ?   @state()
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :          ?   ^
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at failureErrorWithLog (.../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:1650:15)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at .../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:1058:25
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at runOnEndCallbacks (.../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:1485:45)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at buildResponseToResult (.../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:1056:7)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at .../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:1068:9
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at new Promise (<anonymous>)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at requestCallbacks.on-end (.../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:1067:54)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at handleRequest (.../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:731:17)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at handleIncomingPacket (.../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:756:7)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Socket.readFromStdout (.../flow-hilla-hybrid-example/node_modules/esbuild/lib/main.js:679:7)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Socket.emit (node:events:514:28)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at addChunk (node:internal/streams/readable:324:12)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at readableAddChunk (node:internal/streams/readable:297:9)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Readable.push (node:internal/streams/readable:234:10)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [TypeScript] Found 0 errors. Watching for file changes.
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [vite] ? new dependencies optimized: @vaadin/common-frontend/ConnectionIndicator.js, date-fns/format, date-fns/parse, date-fns/isValid, proj4
INFO 12375 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [vite] ? optimized dependencies changed. reloading
```

Doesn't affect the application functionality. Only shows up on the first run with `mvn`.

Versions:

```xml
    <properties>
        <java.version>17</java.version>
        <vaadin.version>24.3.0</vaadin.version>
        <hilla.version>2.5.0.beta1</hilla.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
    </parent>
```

**Comment by mshabarov** [comment]
Might be fixed by https://github.com/vaadin/hilla/pull/1891.

**Comment by mshabarov** [comment]
Isn't reproduced anymore with Hilla 2.5.5.
